### ISSUE TITLE
Izroček 1.1: centralno skladišče dokumentov

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#24]
**Izroček 1.1**: vzpostavljeno centralno skladišče dokumentov na odprtem strežniku, ki lahko vsebuje tekstovne dokumente v zapisih txt, doc, html, xml, pdf (le v berljivi, neskenirani obliki). Repozitorij bo v tej fazi vseboval primere dokumentov s področja zakonov o registrih.

**Comment by PrimozGodec** [comment]
Vzpostavili smo podatkovno skladišče na naslovu
http://file.biolab.si/text-semantics/
Skladišče v tej fazi vsebuje podatke z zakoni o registrih in predloge vladi. Zaenkrat podpiramo dva načina hranjenja podatkov in metapodatkov. V obeh načini je besedilo vsakega dokumenta shrnjeno kot tekstovna datoteka (.txt). Razlika med obema načinoma je v hranjenju meta podatkov. V prvem načinu, ki smo ga kot primer uporabili za hranjenje podatkov o [predlogih vladi](http://file.biolab.si/text-semantics/proposals-to-government/) so meta podatki shranjeni za vsak dokument posebej v datoteki v zapisu YAML (.yaml). Ta dokument mora imeti isto ime kot tekstovni dokument. V drugem načinu, ki smo ga uporabili za zapis podatkov o [zakonih o registrih](http://file.biolab.si/text-semantics/laws/) so vsi metapodatki zbrani v eni sami tabeli, ki jo hrani datoteka metadata.csv. Eden od stolpcev v tej datoteki mora hraniti ime tekstovne datoteke, na katero se podatki v vrstici tabele nanašajo.

**Comment by BlazZupan** [comment]
Dela na tem izročku so zaključena.

**Comment by MLozej** [comment]
Predlagam, da začnemo namesto "podakovno skladišče" uporabljali pojem "podatkovni prostor" - podatkovni prostor nečesa. Na primer: podatkovni prostor slovenske zakonodaje. Značilnosti prostora (po moje) so:
- vsebuje prečiščene in verificirane/uradno veljavne podatke (v našem primeru besedila)
- Vsebuje vse potrebne šifrante in povezave na druge prostore (dokumente), da je možno vsebino podatkov pravilno interpretirati in povezovati (navezava na registre, na primer)
- podatki se redno vzdržujejo in obnavljajo (opredeljene so frekvence obnavljanja). Opredeljeno je, če se hrani zgodovina podatkov. Opredeljeni so tudi postopki za odpravljanje morebitnih napak v podatkih, če so zašle v prostor.
- vsebuje orodja za prevzemanje podatkov iz originalnih virov, osnovno pregledovanje vsebin in osnovna orodja za tehnično podporo (spremljanje obsega in dodeljevanje prostora, rezervne kopije,...)
- v okviru prostora se beležijo potrebni meta podatki za upravljanje in izvajanje potrebnih aktivnbosti (v našem primeru na primer predprocesiranje novih in spremenjenih dokumentov)
- Za vsak podatek v prostoru je opredeljena institucija, ki podatke posreduje, nadzoruje in po potrebi popravlja.
- morda še kaj...

Razmišljam tudi o pojmu "podprostor", ki bi obsegal podatke iz virov, za katere je zadolžena ena institucija - upravljalec podprostora. Ena od nalog skrbnika podprostora je, da opredeli pogoje, katerim mora zadostiti uporabnik. Pri podatkih državne uprave so to običajno zakonske podlage. Pri odprtih podatkih tega ni, pri osebnih podatki pa morajo biti kriteriji zelo omejujoči. Bodoči uporabnik mora upravljalcu posredovati prošnjo z dokazili in nato prejme ustrezna soglasja in pravice za uporabo.

V našem primeru gre za javno dostopne zakonske dokumente (torej nič kriterijev). Zato gre predvsem za zbiranje in predprocesiranje. V neki točki bomo morali opredeliti njihovega upravljalca in mu predati orodja za upravljanje prostora (to bo naloga MJU).

**Comment by BlazZupan** [comment]
@MLozej, se seveda strinjam. Naslov izročka bi sicer pustil, saj ta ustreza naslovom v pogodbi. Ali pa predlagaš, da tudi tu spremenimo izraz podtkovno skladišče v podatkovni prostor? Vsekakor bi se tega predloga potem držali v ostalih poročilih in v dokumentaciji projekta.

**Comment by MLozej** [comment]
Naslove izročkov pustimo kot so, lahko pa v besedilu ugotovimo, da je odslej smiselno uporabljati sodobnejši izraz.

**Comment by BlazZupan** [comment]
Se strinjamo, hvala.

**Comment by mihajMJU** [comment]
Dve zadevi bi dodal k debati tega izročka. V razmislek.
1. Podatkovni prostor (PP): bilo bi koristno, če bi PP skušali čimbolj približati načelom FAIR (https://www.go-fair.org/fair-principles/). Findability je odvisen tudi od zunannjih dejavnikov, zlasti podatkovnega zemljevida javne uprave in katalogov o podatkih in storitvah.

2. Vsebina podatkovnega prostora: ali bi bilo smiselno (bolj učinkovito za semantični analizator?) razširiti nabor obravnavanih besedil vsaj še na podzakonske akte? Veliko definicij zlasti za lastnosti razredov, tudi povezav, sami razredi so povečini v zakonih, je namreč ravno v podzakonskih aktih. Kar je pa še mogoče nekoliko posebno pa je, da je pravna ureditev oziroma tehnika zakonodajnega urejanja neenotna. Pa tudi, da je področje pravno pokrito z zakonom in vsemi njegovimi podzakonskimi akti, k temu je treba še prišteti morebitno relevantnost vplivov, sklicev na druge zakone in podrejene akte. To (tehnika zakonodajnega urejanja neenotna) pomeni, da imamo eno področje lahko urejeno v enem predpisu (recimo v tem primeru, da je en predpis zakon ali zakonik z njegovimi podrejenimi akti), lahko pa  vveč predpisih (več zakonov z njiuhovimi podrejenimi akti). Potem lahko en zakon (s podrejenimi akti) ureja več področij. Potem lahko več zakonov vsak nekaj od več področij. Tipično za večja področja je, da imajo svoj postopkoven ali organizacijski zakon 
Najbolje bi bilo (moj pogled!), če bi imeli nabor celotne zakonodaje, pripravljen kot obdelan korpus in primeren za nadaljnje analize, pri čemer pa bi potem analizirali nek segment. Razmišljam sicer laično, ali bi bilo lahko smiselno, da imamo torej celoten nabor, nato se npr. odločimo analizirati zakonodajo o registrih, potem pa bi z analize tega "registrskega podpodročja", z njegovimi značilnimi pojmi šli iskat sorodne dokumente še v celotnem naboru in potem zopet analizirali sorodnost tega razširjenega podpodročja.

**Comment by mihajMJU** [comment]
Še eno stvar sem pozabil:
Kako bo z dopolnjevanjem prostora? Bo lahko to sam naredil uporabnik (ročno, klik na servis)?, Bo to delal MJU kot lastnik/upravljalec aplikacije (ročno, klik na servis)? Ali pa bo servis (dnevni?)? Gre za nove predpise, spremembe predpisov in razveljavitve predpisov.

**Comment by BlazZupan** [comment]
@mihajMJU, hvala za odlične predloge. Oblikovanje podatkovnega prostora je bil v tej, prvi fazi, namenjen predvsem raziskavam in oblikovanju tehnik za semantično analizo. Skripte za dopolnjevanje podatkov je vsekakor moč dopolnjevati in razširjati, tudi tako, da bi se lahko avtomatično prožile. Vključevanje celotne hierarhije vseh zakonov in podzakonskih aktov je izjemno zanimiva ideja, ki pa po vsebini trenutno presega ta projekt in bi bilo zanimivo o njej razmisliti, čim bomo imeli rezultate na nivoju Orange-a. Predlagam zato, da tudi pri oblikovanju podatkovnega prostora oziroma tam vključenih dokumentov sledimo planu projekta in se na to točko vračamo, ko bodo izpeljani tudi preostali izročki.
