### ISSUE TITLE
Izroček 1.2: centralno skladišče ontologij

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#25]
**Izroček 1.2**: vzpostavljeno centralno skladišče ontologij na odprtem strežniku, ki v tej fazi vsebuje nekaj primerov ontologij zapisanih v obliki owl.

**Comment by PrimozGodec** [comment]
Vzpostavili smo skladišče ontologij na naslovu http://file.biolab.si/text-semantics/ontologies/

Kot primer ontologij, s katerimi smo v tej fazi polnili skladišče, smo uporabili ontologije z izrazi iz SSKJ in ontologija [European Legislation Identifier](https://op.europa.eu/sl/web/eu-vocabularies/eli), ki smo jo prevedli v slovenščino. Ontologije hranimo v obliki OWL (datoteke .owl) ali v obliki RDF (datoteke .rdf).

**Comment by BlazZupan** [comment]
Dela na tem izročku so zaključena.

**Comment by MLozej** [comment]
Predlagam uporabo pojma "podatkovni prostor" (glej izroček 1.1)

**Comment by BlazZupan** [comment]
@MLozej, se strinjam, a tudi tu, kot v izročku 1.1, smo sledili poimenovanju izročka po besedilu iz pogodbe. Kaj predlagaš?

**Comment by MLozej** [comment]
Naslova zaradi navezave na pogodbo ne spreminjamo. V besedilu pa lahko omenimo, da je sedaj primernejši termin "podatkovni prostor" glede na sedaj uveljavljeno dikcijo v dokumentih evropske unije. In od tam ta pojem uporabljamo v dokumentaciji (razen v naslovih).

**Comment by BlazZupan** [comment]
Super, se strinjamo. Diskusija o primernosti izraza je seveda sedaj omenjena in shranjena tudi v tem pogovoru na githubu.

**Comment by mihajMJU** [comment]
Podobno kot zadnji komentar pri izročku 1.1. bi tudi tukaj zapisal:
1. Kako bo potekalo dodajanje, osveževanje in nadomesščanje/odstranjevanje ontologij? BO lahko/moral to narediti uporabnik? Bo to v pristojnosti MJU? BO to servis (MJU mora seveda vzpostaviti dostopen repozitorij veljavnih/potrjenih ontologij)?

2. Ta in še kakšna strokovna poimenovanja (bi se sproti dogovarjali in predlagali ter vklučili) bi vključil v slovar, ki je na koncu PZI. Kar bi bil potem skupek zelo koristnih definicij in informacij.

**Comment by BlazZupan** [comment]
Hvala @mihajMJU za komentarje. S funkcijami spreminjanja ontologij bi se ukvarjali na nivoju programskih vmesnikov. Zaenkrat smo samo določili prostor, kjer te ontologije lahko živijo ter oblikovali bralnike za ontologije. Ontologije bodo zares zaživele v grafičnih vmesnikih, kjer bo implementirano tudi spreminjanje in (sprotno) shranjevanje ontologij.
