### ISSUE TITLE
Izroček 1.3: predobdelava dokumentov

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#26]
**Izroček 1.3:** knjižnica za predobdelavo skladišča dokumentov v namen poenotenja zapisa dokumentov v enostavno berljivo tekstovno obliko.

**Comment by BlazZupan** [comment]
Za ta izroček smo se odločili implementirati skripte, ki znajo pridobiti podatke iz surovih datotek oziroma iz spletnih strani ter te predobdelati in zapisati v obliki, ki je primerna za shranjevanje v repozitoriju projekta. Ker so podatkovni viri različni, predvidevamo, da bo za vsak tip dokumentov oziroma za vsak projekt potrebno spisati svoj del kode za predobdelavo. Kot cilj tega izročka smo zato postavili izdelavo skript za branje spletnih podatkov o predlogih vladi in spletnih podatkov o zakonih.

**Comment by PrimozGodec** [comment]
Pripravili smo dve skripti, ki pridobita podatke iz interneta in jih pretvorita v primerno obliko za prenos v skladišče dokumentov:
- [laws_scraper.py](https://github.com/biolab/text-semantics/blob/main/scripts/laws_scraper.py) pridobi zakone o registrih skupaj z meta podatki s spletnega mesta [Pravno-informacijski sistem -PisRS](http://www.pisrs.si/Pis.web/)
- [proposals_scraper.py](https://github.com/biolab/text-semantics/blob/main/scripts/proposals_scraper.py) pridobi predloge vladi skupaj z meta podatki s spletnega mesta [Predlagam Vladi](https://predlagam.vladi.si/)

**Comment by BlazZupan** [comment]
Dela na tem izročku so zaključena.
