### ISSUE TITLE
Izroček 1.4: branje podatkov iz skladišča

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#27]
**Izroček 1.4**: primeri skript v jeziku Python, ki berejo predobdelane dokumente in ontologije iz vzpostavljenih skladišč.

**Comment by PrimozGodec** [comment]
Vzpostavili smo prvo verzijo [knjižnice za branje podatkov iz repozitorija](https://github.com/biolab/text-semantics). Spisana je [osnovna dokumentacija](https://github.com/biolab/text-semantics#usage). Implementirali smo tudi primere uporabe:
- [01-01-loading-documents.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/01-01-loading-documents.ipynb) branje dokumentov iz repozitorija, izpis osnovne statistike
- [01-02-ontologies.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/01-02-ontologies.ipynb) branje ontologij, prikaz ontologije v drevesni strukturi

**Comment by BlazZupan** [comment]
Dela na tem izročku so zaključena.

**Comment by mihajMJU** [comment]
Zgleda dobro! Ali bo možno izbirati samo iz celotnega nabora korpusov in ontologij ali pa bo mogoče tudi izbrati posamičen korpus oziroma ontologijo oziroma iskati/ožati te celotne nabore? V smislu klica s ključno besedo.

**Comment by BlazZupan** [comment]
Tole je odličen komentar. Zaenkrat lahko ta izbor delamo v kodi, torej v Python-u, nam pa je komentar dobro vodilo za to, kako bi lahko oblikovali uporabniški vmesnik. Ta bi lahko prebral dokumente in samo njihove karakteristične izraze (meta podatki), ne bi pa iz strežnika prenesel vseh vsebin. Izvedljivo, ampak predlagamo, da počaka na oblikovanje grafičnega vmesnika in da razvoj na tem delu prenesemo tja. S tem bi to poglavje tu, torej o branju podatkov, pustil zaprto.
