### ISSUE TITLE
Izroček 1.5: Projekt za izvedbo

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#28]
**Izroček 1.5**: Izdelati PZI (Projekt za izvedbo) po navodilih dokumenta GTZ.

**Comment by PrimozGodec** [comment]
Trenutna (nedokončna) verzija Projekta za izvedbo je objavljena na [v skladišču dokumentov](http://file.biolab.si/text-semantics/PZI.docx). Dokument je zaklenjen z geslom, ki ga dobite pri meni.

**Comment by PrimozGodec** [comment]
Oddali smo Projekt za izvedbo. Oddana verzija PZIja je objavljena v [skladišču dokumentov](http://file.biolab.si/text-semantics/SA-PZI-V01.docx). Dokument je zaklenjen z geslom, ki ga dobite pri meni.

**Comment by BlazZupan** [comment]
PZI je oddan, MJU (Miha, Miro) je dokument pregledal, predan je na "višje inštance".

**Comment by mihajMJU** [comment]
Dokument PZI je ustrezen, dogovorili smo se pa, da se dodata še dve zadevi. Prva je skica namestitev s potrebnimi (glavnimi) tehnološkimi elementi. Torej kaj obsega arhitektura sistema semantičnega analizatorja in kako bo izgledala namestitev te arhitekture na izbranem okolju. Druga zadeva pa je dopolnitev besedila (najbrž v okviru poglavja 1.4) s poudarjeno navezavo na podatkovne strukture iz korpusa zakonodajnih besedil za gradnjo/vzdrževanje ontologij.
