### ISSUE TITLE
Izroček 2.3: vektorska predstavitev dokumentov, dokumentne karte

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#31]
**Izroček 2.3**: knjižnica in primeri uporabe metod za vektorsko predstavitev dokumentov in izris kart dokumentov.

**Comment by PrimozGodec** [comment]
V [03_03_document_maps.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/03_03_document_maps.ipynb) pridobimo 100 dokumentov iz zbirke [predlogov vladi](http://file.biolab.si/text-semantics/data/predlogi-vladi/), jih preprocesiramo in izračunamo njihove vložitve (vektorska predstavitev dokumentov). Dokumente predstavimo v karti dokumentov, ki jo pripravimo s pomočjo metode [UMAP](https://arxiv.org/abs/1802.03426). S pomočjo metode [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN) najdemo skupine podobnih dokumentov in te označimo v karti z barvami. Za vsako skupino izpišemo zanjo specifične besede - te predstavijo skupno temo predlogov v skupini. Za konec izpišemo besedila treh dokumentov iz vsake izmed skupin, da se prepričamo o njihovi smiselnosti.

**Comment by BlazZupan** [comment]
Dela na tem izločku so zaključena.

**Comment by mihajMJU** [comment]
Ali bi bilo možno in kako kompleksno (obsežno, zahtevno) delo bi bilo, da bi npr. uporabnik določil skupine in izbral ključne besede teh skupin (iz ontologije ali da bi jih vpisal sam oz. iz navadnega besedila), orodje bi pa potem razporedilo dokumente v te skupine (kolikor bi bilo primernih) in v dodatne skupine tiste, ki ne bi ustrezali predlaganim skupinam?

**Comment by PrimozGodec** [comment]
> Ali bi bilo možno in kako kompleksno (obsežno, zahtevno) delo bi bilo, da bi npr. uporabnik določil skupine in izbral ključne besede teh skupin (iz ontologije ali da bi jih vpisal sam oz. iz navadnega besedila), orodje bi pa potem razporedilo dokumente v te skupine (kolikor bi bilo primernih) in v dodatne skupine tiste, ki ne bi ustrezali predlaganim skupinam?

Smo že razmišljali o izboru uporabnikovih besed in iskanju skupin glede na te besede. To funkcionalnost bomo poskusili vpeljati v orodje, ki ga bomo razvili v okviru faze 3.

**Comment by BlazZupan** [comment]
@mihajMJU, funkcionalnosti, ki jih predlagate, so predvidene za raziskavo v tretji fazi in neposredno povezane z oblikovanjem ustreznih uporabniških vmesnikov, česa se lotevamo neposredno po zaključku druge (te) faze projekta.
