### ISSUE TITLE
Izroček 2.4: vektorska predstavitev izrazov, karte izrazov

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#32]
**Izroček 2.4**: knjižnica in primeri uporabe metod za vektorsko predstavitev izrazov in izris kart izrazov.

**Comment by PrimozGodec** [comment]
V [03_04_vector_representation_of_words.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/03_04_vector_representation_of_words.ipynb) pridobimo besedila 100 [predlogov vladi](http://file.biolab.si/text-semantics/data/predlogi-vladi/), jih preprocesiramo in iz njih izluščimo besede. Besede predstavimo z vektorji s pomočjo vložitve imenovane [fastText](https://fasttext.cc/) in jih prikažemo v karti izrazov. Tiste besede, ki so podobne, so v karti blizu skupaj. V karti z barvami označimo skupine podobnih izrazov. Da se prepričamo o podobnosti izrazov v skupinah, izpišemo izraze v eni izmed skupin.

**Comment by BlazZupan** [comment]
Dela na tem izročku so zaključena.

**Comment by mihajMJU** [comment]
Kako, da sta tukaj samo dve skupini? Ali so prikazani tudi izrazi dokumentov, ki niso v skupini? Oziroma ali je možno videti tudi izraze dokumentov, ki se niso razvrstili vnobeno skupino? Ali je tudi možno videti, v katerih dokumentih se izraz/izrazi pojavljajo?

**Comment by ajdapretnar** [comment]
@mihajMJU 
- Dve skupini sta zato, ker embedding ločuje med glagoli in ne-glagoli. Posledično nastane ločena skupina za glagole (na levi). Sicer pri tem ne gre v resnici za skupino v smislu gručenja. DBSCAN vrne 338 skupin dokumentov, 381 dokumentov ne pripada nobeni skupini.
- Prikazani so zgolj izrazi izbrane skupine. Možno je zamenjati izbor in prikazati izraze iz izbrane skupine. Ali dodam primer, kjer so prikazani izrazi dokumentov, ki jih DBSCAN ni razvrstil v nobeno od skupin?
- Lahko dopišemo še ID-je ali pa recimo naslove dokumentov izbrane skupine.

Pri tem je seveda vprašanje, ali je to mišljeno za shematski prikaz v skriptah ali je to namenjeno kasnejši implementaciji v uporabniškem vmesniku?
