### ISSUE TITLE
Izroček 2.5: iskanje ključnih besed, razlaga

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#33]
**Izroček 2.5**: knjižnica in primeri uporabe metod za razlago dokumentnih in izraznih kart.

**Comment by BlazZupan** [comment]
V sklopu tega izročka se odločimo raziskati, implementirati in ovrednotiti tehnike za iskanje ključnih besed. Posamezen dokument, ali pa skupino dokumentov bomo tako skušali predstaviti s pripadajočimi ključnimi besedami in na ta način tudi "razložili" gruče v dokumentnih kartah. Iskanje ključnih besed bo pomembno tudi pri določitvi izrazov, s katerimi bi lahko obogatili obstoječe ontologije, ter pri kakršnikoli analizi in povzemanju dokumentov.

Naloge tega izročka so zato:
- pregled stanja raziskav in metod za iskanje ključnih besed,
- pridobitev korpusa v slovenskem jeziku, kjer so za posamezne dokumente ključne besede podane in ki ga lahko uporabimo za vrednotenje,
- izbor tehnike za vrednotenje in načina merjenja točnosti,
- implementacija metod za iskanje ključnih besed,
- eksperimentalno vrednotenje.

**Comment by PrimozGodec** [comment]
Pregled stanja raziskav, pridobitev korpusa, izbor, implementacijo in vrednotenje tehnik za iskanje ključnih besed smo izvedli v okviru [dodatnega izročka 2.X](https://github.com/biolab/text-semantics/issues/50).

V okviru tega izročka smo izvedli razlago dokumentnih kart s pomočjo implementacij, ki smo jih izvedli v izročku 2.X.
- v [04_08_document_maps_explanation.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/04_08_document_maps_explanation.ipynb) smo izvedli razlago dokumentnih kart predlogov vladi
- v [04_08b_document_maps_explanation-laws.ipynb ](https://github.com/biolab/text-semantics/blob/main/examples/04_08b_document_maps_explanation-laws.ipynb) smo izvedli razlago dokumentnih kart zakonov

**Comment by BlazZupan** [comment]
Ta izroček je zaključen. Razširjen je bil tudi z dodatnim izročkom, kjer smo primerjali rezultate [tehnik iskanja ključnih izrazov](https://github.com/biolab/text-semantics/issues/50).
