### ISSUE TITLE
Izroček 2.X: vrednotenje in primerjava tehnik za iskanje ključnih besed

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#50]
Pripravimo korpus, kjer so dokumenti že označeni s ključnimi besedami (npr. članki v revijah). Na tem korpusu primerjamo tehnike za iskanje ključnih besed. Cilj je identificirati omejeno število tehnik, katerih točnost bi bila najboljša in katere bi potem uporabili v grafičnem uporabniškem vmesniku.

Izroček ni bil prvotno vključen v projekt, a smo ga opcijsko vključili, saj nam koristi pri nadaljnjem delu.

**Comment by PrimozGodec** [comment]
Pripravili smo štiri korpuse z že označenimi dokumenti. Dva v slovenščini in dva v angleščini.
- [Članki iz revije Prispevki za novejšo zgodovino](http://file.biolab.si/text-semantics/data/CTCH/) - [01-03-CTCH-exploration.ipynb ](https://github.com/biolab/text-semantics/blob/main/examples/01-03-CTCH-exploration.ipynb ) na kratko predstavi ta korpus.
- [Članki iz revije Elektrotehniški vestnik](http://file.biolab.si/text-semantics/data/elektrotehniski-vestnik-clanki/ ) - [01-04-el.vestnik-exploration.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/01-04-el.vestnik-exploration.ipynb ) na kratko prestavi ta korpus.
- [Nabor besedil Semeval](http://file.biolab.si/text-semantics/data/semeval/) - [Semeval](https://www.aclweb.org/anthology/S10-1004/) je korpus, ki ga sestavlja 244 člankov s področja računalništva
- [Nabor besedil Shultz2008](http://file.biolab.si/text-semantics/data/schutz2008/) - [Schultz2008](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.394.5372) je korpus, ki ga sestavlja 1232 člankov s področja medicine.

Na zgoraj omenjenih člankih smo primerjali več pristopov za luščenje ključnih besed: [TF-IDF](https://github.com/biolab/text-semantics/blob/main/examples/04_03_specific_words_with_tfidf.ipynb), [pristop z vekorskimi vložitvami](https://github.com/biolab/text-semantics/blob/main/examples/04_01_specific_words_with_embeddings.ipynb), [RAKE](https://github.com/biolab/text-semantics/blob/main/examples/04_04_specific_words_graph_base.ipynb ), [Yake!](https://onlinelibrary.wiley.com/doi/abs/10.1002/9780470689646.ch1) in [TextRank](https://github.com/biolab/text-semantics/blob/main/examples/04_04_specific_words_graph_base.ipynb). Objektivne primerjave so predstavljene v naslednjih zvezkih: 
- Primerjava na člankih v prispevkih za novejšo zgodovino: [04_06_specific_words_comparison_ctch.ipynb ](https://github.com/biolab/text-semantics/blob/main/examples/04_06_specific_words_comparison_ctch.ipynb )
- Primerjava na člankih iz elektrotehniškega vestnika: [04_07_specific_words_comparison_el_vestnik.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/04_07_specific_words_comparison_el_vestnik.ipynb )

Za referenco smo primerjali tudi pristope na besedili na katerih so primerjavo izvedli v literaturi. Gre za besedila v angleščini.
- Primerjava na naboru besedil Semeval je predstavljena v [04_08_specific_words_comparison_schutz2008.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/04_08_specific_words_comparison_schutz2008.ipynb)
- Primerjava na naboru besedil Shultz2008 je predstavljena v [04_09_specific_words_comparison_semeval.ipynb](https://github.com/biolab/text-semantics/blob/main/examples/04_09_specific_words_comparison_semeval.ipynb)

**Comment by BlazZupan** [comment]
Rezultati primerjave so res zanimivi. Med primerjavo so se tudi optimizirale nekatere tehnike, na primer vložitve v vektorske prostore z globokimi modeli. Ta pristop, ob uporabi korpusa, po kvaliteti sedaj celo prednjači na slovenskih besedilih. Tako, da bi bilo najbrž komentar na koncu primerjave, ki pravi "Iz grafov lahko sklepamo, da se na primeru člankov iz revije Elektrotehniški vestnik najbolje obneseta metodi TF-IDF in YAKE!. Sledi TextRank. Podobno se obneseta metodi z vložitvami, najslabše pa se obnese metoda RAKE." spremeniti oziroma osvežiti?

**Comment by ajdapretnar** [comment]
Če prav vidim, zgornja trditev še vedno velja. Ali govorimo o 04_07_specific_words_comparison_el_vestnik.ipynb?

**Comment by BlazZupan** [comment]
Se opravičujem, tule je prišla do izraza moja delna barvna slepota. Kar pomeni, da bi bilo dobro nekaj spremeniti v grafih. Kasneje, ni nujno, ampak pri člankih pa prav gotovo. YAKE in TF-IDF sta torej najboljša, in to konsistentno. Premisliti bo potrebno še o uporabi nadpomenk, kjer bo problem slovenščina. O tem bi razmišljali drugje.
