### ISSUE TITLE
Izroček X: Vzpostavitev skupnosti

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#68]
Izroček X: Izvajalec bo vzpostavil in vodil skupnost na način, kot je to določeno v prilogi 3 pogodbe ter v pogodbi, za obdobje 24 mesecev. 

Komunikacija s skupnostjo naj poteka preko spletne strani, ki naj med drugim omogoča:
- Izmenjavo mnenj in izkušenj med uporabniki
- Promocijo izvedenih primerov uporabe
- Vprašanja o uporabi
- Pomoč in nasveti pri uporabi
- Zbiranje predlogov za dopolnitev in izboljšave rešitve

**Comment by PrimozGodec** [comment]
Navodila za sodelovanje v skupnosti:

Skupnost je vzpostavljena na repozitoriju projekta preko razdelka **Issues**: https://github.com/biolab/text-semantics/issues

Uporabnik, ki želi sodelovati v skupnosti, lahko:
    
1. **Pregleduje obstoječe razprave**, ki jih najde na seznamu na [posredovani povezavi](https://github.com/biolab/text-semantics/issues). 

2. **Komentira in sodeluje v obstoječih razpravah**. To stori tako, da klikne na obstoječo razpravo v seznamu, in v tekstovnem polju na dnu okna doda svoj komentar.

3. **Odpre novo razpravo**. Za odpiranje nove razprave 1) uporabi gumb **New issue** v zgornjem desnem kotu strani, 2) vpiše željeni komentar v tekstovno polje in 3) objavi svoj komentar s klikom na gumb **Submit new issue**.
    
Za komentiranje in odpiranje razprave mora uporabnik [ustvariti račun na platformi GitHub](https://github.com/join?ref_cta=Sign+up).

**Comment by mihajMJU** [comment]
Projekt je sofinanciran s strani Evropske Unije.
![logotipi](https://user-images.githubusercontent.com/77438954/121521483-6cd47c00-c9f4-11eb-8823-674cade6fcf2.jpg)

**Comment by PrimozGodec** [comment]
V https://github.com/biolab/text-semantics/pull/71 dodajam opis projekta v README (na prvo stran repozitorija). Opis vključuje tudi navodila za skupnost. Komentarji na opis dobrodošli.

**Comment by PrimozGodec** [comment]
V pull reqestu #71 smo dodali opis projekta in navodila za skupnost. Opis in navodila se nahajajo na [začetni strani repozitorija](https://github.com/biolab/text-semantics).

**Comment by mihajMJU** [comment]
> 
> 
> Skupnost je vzpostavljena na repozitoriju projekta preko razdelka **Issues**: https://github.com/biolab/text-semantics/issues. Skupnost smo vzpostavili z odprtjem tega repozitorija 10. novembra 2020.
> 
> Navodila za sodelovanje v skupnosti:
> 
> Uporabnik, ki želi sodelovati v skupnosti, lahko:
> 
>     1. **Pregleduje obstoječe razprave**, ki jih najde na seznamu na [posredovani povezavi](https://github.com/biolab/text-semantics/issues).
> 
>     2. **Komentira in sodeluje v obstoječih razpravah**. To stori tako, da klikne na obstoječo razpravo v seznamu, in v tekstovnem polju na dnu okna doda svoj komentar.
> 
>     3. **Odpre novo razpravo**. Za odpiranje nove razprave 1) uporabi gumb **New issue** v zgornjem desnem kotu strani, 2) vpiše željeni komentar v tekstovno polje in 3) objavi svoj komentar s klikom na gumb **Submit new issue**.
> 
> 
> Za komentiranje in odpiranje razprave mora uporabnik [ustvariti račun na platformi GitHub](https://github.com/join?ref_cta=Sign+up).

Pri 3. **Odpre novo razpravo.** je treba določiti še naslov zadeve (Issue). Če gre za zadevo, ki obravnava temo katerega izmed izročkov, naj naslov sledi naslovom dosedanjih zadev, npr. Izroček 3.4: _Razvoj delotokov in ustreznih komponent za izris in interaktivno analizo pojmov_.
Če gre za druge zadeve, se lahko uporabi splošen naslov za nove zadeve, torej za nove razprave, ki bodo obravnavale razne vidike orodja, npr. Ostalo X: {_vaš izbran naslov_}
