### ISSUE TITLE
Izroček 3.1: Razvoj komponente za dostop, branje in prikaz dokumentov iz strežniškega repozitorija

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#74]
V sklopu tega izročka razvijemo komponente z grafičnim vmesnikom v okolju Orange, s katerimi lahko dostopami do korpusov na strežniškem repozitoriju in dokumente iz korpusa tudi pregledamo. V sklopu tega izročka tako razvijemo oziroma nadgradimo naslednje gradnike:
* **Import Documents**, za branje podatkov
* **Corpus Viewer**, za prikaz prebranih dokumentov

**Comment by PrimozGodec** [comment]
Nadgradili smo obstoječ gradnik Import Documents, ki sedaj podpira tudi nalaganje dokumentov iz strežniškega repozitorija. Za prikaz dokumentov je na voljo obstoječi gradnik Corpus Viewer.

**Comment by BlazZupan** [comment]
Ta izroček je dokončan in se že uporablja.
