### ISSUE TITLE
Izroček 3.2: Razvoj komponente za dostop, branje in prikaz ontologij iz strežniškega repozitorija

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#75]
V sklopu tega izročka razvijemo komponento z grafičnim vmesnikom za dostop in branje ontologij pojmov iz strežniškega repozitorija. Komponenta prikaže ontologije in omogoča izbor pojmov iz ontologije, ki se lahko posredujejo ostalim komponentam sistema za semantično preiskovanje in izbor dokumentov.

**Comment by PrimozGodec** [comment]
Razvili so gradnik Ontology, ki avtomatsko zgradi ontologijo iz besed, ki jih prejme na vhodu in ontologijo prikaže v drevesni strukturi. Bralnik ontologij iz strežniškega repozitorija je implementiran v knjižnici in ga zaenkrat lahko uporabimo v gradniku Python Script. Delo na tem izročku je pokazalo na možnosti izgradnje interaktivnega pripomočka za gradnjo in urejanje ontologij, kjer izhajamo samo iz seznama gesel, ali pa kombiniramo ta z obstoječimi ontologijami. Omenjena funkcionalnost, s katero se trenutno ukvarjamo raziskovalno, bo morala biti podprta tudi preko ustreznih uporabniških vmesnikov, katerih izdelavo bi želeli predlagati v razširitvi tekočega projekta.

**Comment by BlazZupan** [comment]
Gradnik je razvit. Tekom projekta se je izkazalo, da bi gradnja in uporaba ontologij lahko bila še bolje raziskana, nakazuje se nova smer razvoja in možnih uporab.
