### ISSUE TITLE
Izroček 3.3: Delotok in ustrezne komponente za izris in interaktivno analizo kart dokumentov

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#76]
V sklopu tega izročka razvijemo niz komponent, s katerimi lahko izrišemo karte dokumentov in te analiziramo s stališča semantične podobnosti in pojmov, ki jih izbere uporabnik. V sklopu tega izročka načrtujemo razvoj sledečih gradnikov:
* **Word List**, upravljanje s seznami pojmov, to je branje seznamov, spreminjanje seznamov in izbor pojmov iz seznama
* **Extract Keywords**, za dani dokument ali skupino gradnik izloči karakteristične pojme, jih prikaže in omogoči izbor
* **Score Documents**, za vhodni korpus in množico pojmov gradnik poda oceno, kako specifični so pojmi za posamezen dokument
* **Annotated Document Map**, gradnik na karti pokaže dokumente, jih uredi v skupine in te opiše s karakterističnimi pojmi

**Comment by PrimozGodec** [comment]
Razvili smo gradnik Word List, kjer lahko uporabnik pripravi sezname pojmov, med njimi preklaplja in jih shrani. Gradnik omogoča tudi nalaganje seznamov pojmov iz datotek in njihovo shranjevanje v datoteke. Gradnik lahko prejme tudi seznam pojmov iz drugih gradnikov.
Razvili smo gradnik Extract Keywords, ki iz besedil na vhodu izlušči ključne izraze. Za luščenje izrazov lahko uporabnik izbira med štirim metodami: TF-IDF, YAKE!, Rake in metodo na podlagi vektorskih vložitev.
Razvili smo gradnik Score Documents za točkovanje dokumentov na podlagi besed, ki jih gradnik dobi na vhodu. Gradnik v kombinaciji z gradnikom t-SNE omogoča prikaz označenih dokumentnih map (Annotated Document Map).
Delotok, ki vključuje vse razvite komponente, in ki v kombinaciji omogoča izrise in interaktivno analizo kart dokument, prikazujemo spodaj.

**Comment by PrimozGodec** [comment]
![izrocek3](https://user-images.githubusercontent.com/6421558/144743091-e904a52e-a0ce-4aed-87d3-39c81e4cef72.png)

**Comment by PrimozGodec** [comment]
<img width="1313" alt="Screenshot 2021-12-05 at 11 46 01" src="https://user-images.githubusercontent.com/6421558/144743369-0b3ddf01-058d-4589-a375-d9f85cb3f2d9.png">

**Comment by BlazZupan** [comment]
Dokončano. Gradnike na primerih uporablja tudi naročnik.
