### ISSUE TITLE
Izroček 3.4:  Razvoj delotokov in ustreznih komponent za izris in interaktivno analizo pojmov

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#77]
Ta izroček bodo predvidoma funkcionalno pokrili gradniki razviti v izročkih 3.1 do 3.3, njihovo uporabnost pa prikažemo z ustreznimi delotoki.

**Comment by PrimozGodec** [comment]
Zahteve tega izročka smo pokrili s komponentami razvitimi v izročkih 3.1 in 3.3. Primer delotoka, ki vključuje razvite komponente, prikazujemo spodaj.

**Comment by PrimozGodec** [comment]
![faza4](https://user-images.githubusercontent.com/6421558/144743165-40de0f71-7fe1-44fe-a631-a16a51b0849f.png)

**Comment by BlazZupan** [comment]
Dokončano. Gradnike na primerih uporablja tudi naročnik, funkcionalnosti pa smo tudi že predstavili na sestankih in konferencah.
