### ISSUE TITLE
Izroček 3.5: Razvoj delotokov za združeno interaktivno analizo dokumentov, ontologij in pojmov

### ISSUE THREAD

**Issue by BlazZupan** [biolab/text-semantics#78]
V izročku razvijemo delotoke, ki na primerih prikažejo delovanje vse gradnikov za semantično analizo besedil skupaj. Pripravimo podatke, primere analize, in delokroge, ter o njih poročamo na blogih in v seznamih delokrogov, ki jih objavimo tu in nekatere na spletnih straneh programa Orange.

**Comment by PrimozGodec** [comment]
Pripravili smo delotok, ki prikaže delovanje vseh razvitih gradnikov. Delotok, ki ga prikazujemo spodaj, je samo primer možnosti kombinacije gradnikov, ki so bili razviti v projektu. Nekatere od teh kombinacij smo sicer dodatno predstavili oziroma jih nameravamo predstaviti na dogodkih, ki vključujejo 28. konferenco Dnevi slovenske informatike 2021 (oktober 2021), konferenco SEMIC (december 2021) in delavnico Visokozmogljivo računalništvo in umetna inteligenca v javni upravi (december 2021).

**Comment by PrimozGodec** [comment]
![izrocek5](https://user-images.githubusercontent.com/6421558/144743203-2b75d5d3-626c-4256-9108-c0492fa44a4e.png)

**Comment by BlazZupan** [comment]
Razvoj na tem izročku je zaključen.
