### ISSUE TITLE
Izroček 4.1: Namestitveni paket, namestitvena dokumentacija.

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#86]
Pripravili bomo namestitveni paket (angl. wheel), ki bo objavljen na repozitoriju PyPI – The Python Package Index. Paket bo na voljo za namestitev v Orange kot dodatek (angl. add-on).

**Comment by PrimozGodec** [comment]
Pripravili smo paket in ga naložili na [repozitorij PyPI](https://pypi.org/project/Orange3-Text/)). Prav tako smo pripravili [navodila za namestitev orodja)[https://github.com/biolab/text-semantics/wiki/Navodila-za-namestitev-orodja-semanti%C4%8Dni-analizator]

**Comment by BlazZupan** [comment]
Delo na izročku je dokončano.

**Comment by mihajMJU** [comment]
Prosim, če lahko v navodila za namestitev dodate v 1. točki na koncu nov stavek: 
Možnosti, ki se pojavljajo ob nastavitvi, sprejmemo, kot so predlagane, in jih ne spreminjamo. Med namestitvijo programa Orange se pojavi tudi okno za namestitev Miniconda Python s čimer se tudi strinjamo in sledimu poteku namestitve s potrditvijo vseh predlaganih nastavitev.

Prosim, če dodate nova stavka tudi v točko 2, in sicer takoj za drugim stavkom:
Uslužbenci v državni upravi, ki nameščajo program v službi ali prek VPN morajo v meniju na vrhu zaslona izbrati Options>Settings in ko se odpre okno z novimi možnostmi, med zavihki izberemo zavihek »Network«. V obe okni vnesemo naslov »proxy.gov.si« in kliknemo na gumb »Close«.

**Comment by PrimozGodec** [comment]
@mihajMJU v navodila sem dodal predlagano
