### ISSUE TITLE
Izroček 4.2: Dokumentirani primeri uporabe (delotoki)

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#87]
Primeri uporabe bodo implementirani kot delotoki, ki bodo uporabili vse na novo implementirane komponente iz prejšnjih točk in prikazali celotno analizo. Primeri uporabe bodo dodani paketu na repozitrojiu https://github.com/biolab/text-semantics. Na voljo bodo v podmapi workflows.

**Comment by PrimozGodec** [comment]
Pripravili smo primere uporabe (delotoke), ki se nahajajo na tem repozitorijo v mapi [workflows](https://github.com/biolab/text-semantics/tree/main/workflows). 

Delotoki se nahajajo tudi na [spletni strani](https://orangedatamining.com/workflows/Text-Mining/), kjer so tudi dodatno dokumentirani.

**Comment by BlazZupan** [comment]
Primeri uporabe in delokrogi so objavljeni na spletni strani paketa Orange, glej geslo Text Mining. Delo na izročku je dokončano.

**Comment by mihajMJU** [comment]
Lepo prosim, če lahko dodate med delotoke v mapo workflows in na spletno stran še delotok s funkcionalnostmi delotoka iz https://github.com/biolab/text-semantics/issues/78, ki združuje dve različni zbirki dokumentov.

**Comment by PrimozGodec** [comment]
> Lepo prosim, če lahko dodate med delotoke v mapo workflows in na spletno stran še delotok s funkcionalnostmi delotoka iz #78, ki združuje dve različni zbirki dokumentov.

Pripravili smo omenje delotok in ga dodali v mapo workflows na tem repozitoriju https://github.com/biolab/text-semantics/blob/main/workflows/text-combined-analysis-proposals-laws.ows
