### ISSUE TITLE
Izroček 4.3: Video predstavitev v projektu razvitih funkcionalnosti

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#88]
Video prestavitev bo pripravljena po vzoru video tečajev na https://youtube.com/orangedatamining. Objavljena bo na Orange kanalu na portalu youtube.com.

**Comment by PrimozGodec** [comment]
Pripravili in objavili smo tri videe:
- [Semantic Word Maps and Clusters](https://www.youtube.com/watch?v=f5xR72y43Rs&ab_channel=OrangeDataMining)
- [Semantic Analysis of Text - Loading Text Corpus from the Document Repository
](https://www.youtube.com/watch?v=OgOqABY8o5w&ab_channel=OrangeDataMining)
- [Semantic Document Maps and Clusters
](https://www.youtube.com/watch?v=I2bk09bzGE8&t=3s&ab_channel=OrangeDataMining)

**Comment by BlazZupan** [comment]
Dela na tej aktivnosti so zaključena.
