### ISSUE TITLE
Izroček 4.5: Strežniška implementacija orodja oziroma dostop do programa Orange

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#90]
Pripravili bomo strežniško verzijo programa Orange s prednaloženimi potrebnimi dodatki (angl. add-ons), ki bo nameščena na strežniku v okolju HPC-SLING.

**Comment by BlazZupan** [comment]
Izdelava strežniške vsebnika je končana. Interno smo na Univerzi v Ljubljani tudi poskusno uporabili izdelano okolje in njegovo delovanja preskusili v brskalniku. Lokalna uporaba programa Orange je identična temu v brskalniku, zaradi spletnega prenosa vsebine zaslone pa deluje nekoliko počasneje. Namestitev programa Orange na strežniku z vsebniki priporočamo le takrat, ko bi pri lokalni uporabi prihajalo do problemov delovanja zaradi premajhne količine spomina. Trenutni primeri problemov, ki smo jih obdelovali v projektu, strežniške namestitve ne zahtevajo.
