### ISSUE TITLE
Izroček 5: Nadgradnja gradnika Ontology

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/text-semantics#92]
Nadgradnja gradnika Ontology z dopolnjeno uporabniško dokumentacijo za uporabo uporabniškega vmesnika ter implementacija gradnika v objavno 
različico vmesnika za analizo besedil Orange

**Comment by PrimozGodec** [comment]
Gradnik Ontology smo nadgradili z algoritmom za avtomatično gradnjo ontologij iz besed na vhodu. Prav tako je bil implementiran algoritem za avtomatično umeščanje novih besed v obstoječo ontologijo. Gradnik je na voljo v [najnovejši različici Orangovega dodatka za analizo besedil](https://pypi.org/project/Orange3-Text/)

**Comment by BlazZupan** [comment]
Delo na gradniku Ontology je dokončano. Gradnik je dostopen v orodju Orange.

**Comment by mihajMJU** [comment]
Lepo prosim še za opis gradnika Ontology v dokumentaciji Orange3 Text Mining (https://orange3-text.readthedocs.io/en/latest/index.html), da lahko premaknem kartico.

**Comment by mihajMJU** [comment]
Tu bi rabili še en workflow, da izberem pojem oziroma pojme iz ontologije in grem z njimi iskat v zbirko zakoni najbolj sorodne zakone glede na izbrane pojme. Tega bi potem dodali tudi v mapo workflows in na spletno stran z delotoki.

**Comment by PrimozGodec** [comment]
> Lepo prosim še za opis gradnika Ontology v dokumentaciji Orange3 Text Mining (https://orange3-text.readthedocs.io/en/latest/index.html), da lahko premaknem kartico.

Dokumentacija je sedaj na voljo na https://orange3-text.readthedocs.io/en/latest/widgets/ontology.html

**Comment by PrimozGodec** [comment]
> Tu bi rabili še en workflow, da izberem pojem oziroma pojme iz ontologije in grem z njimi iskat v zbirko zakoni najbolj sorodne zakone glede na izbrane pojme. Tega bi potem dodali tudi v mapo workflows in na spletno stran z delotoki.

Pripravili smo delotok, ki uporabi pojme iz ontologije, z njimi točkuje zakone in v dokumentni mapi izpostavljeno prikaže zakone, ki se nanašajo na izbrane besede. Delotok je v mapi workflows na tem repozitoriju https://github.com/biolab/text-semantics/blob/main/workflows/text-ontology-document-maps.ows
